### ISSUE TITLE
Install-Package Framework Version Error

### ISSUE THREAD

**Issue by joaopedronardari** [MrWindows/MrWindows#1]
Quando executo o comando Install-Package mrwindows obtenho o seguinte erro falando da versão do .NET framework:

Install-Package : Could not install package 'mrwindows 0.3.1.0'. You are trying to install this package 
into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more information, contact the 
package author.

**Comment by joaopedronardari** [comment]
Atualizei para o 4.5.1 e funcionou =D

**Comment by andrecarlucci** [comment]
Legal!
Se precisar de alguma nova funcionalidade abre uma issue aí :)

André Carlucci
twitter/andrecarlucci
Microsoft MVP
Intel Innovator
www.andrecarlucci.com

**Comment by joaopedronardari** [comment]
Opa Claro! Vlw Carlucci =D
